import re

with open('app/src/main/java/com/example/ui/screens/AdminScreen.kt', 'r') as f:
    content = f.read()

# Add Coil AsyncImage import
if "import coil.compose.AsyncImage" not in content:
    content = content.replace("import androidx.compose.ui.platform.LocalContext", "import androidx.compose.ui.platform.LocalContext\nimport coil.compose.AsyncImage\nimport androidx.compose.ui.layout.ContentScale\nimport androidx.compose.foundation.background\nimport androidx.compose.ui.graphics.Brush")

# Helper function for default images
helper_func = """
fun getProductImage(name: String, url: String): String {
    if (url.isNotEmpty()) return url
    val n = name.lowercase()
    return when {
        n.contains("plátano") || n.contains("platano") || n.contains("banana") -> "https://images.unsplash.com/photo-1481349518771-20055b2a7b24?w=500&q=80"
        n.contains("manzana") -> "https://images.unsplash.com/photo-1560806887-1e4cd0b6f447?w=500&q=80"
        n.contains("naranja") -> "https://images.unsplash.com/photo-1547514701-42782101795e?w=500&q=80"
        n.contains("fresa") -> "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=500&q=80"
        n.contains("sandía") || n.contains("sandia") -> "https://images.unsplash.com/photo-1587049352847-4d4b12405407?w=500&q=80"
        n.contains("melón") || n.contains("melon") -> "https://images.unsplash.com/photo-1589739900243-4b52cd9b104e?w=500&q=80"
        n.contains("tomate") || n.contains("jitomate") -> "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500&q=80"
        n.contains("cebolla") -> "https://images.unsplash.com/photo-1618512496248-a0bfe71ada8c?w=500&q=80"
        n.contains("limón") || n.contains("limon") -> "https://images.unsplash.com/photo-1590502593747-422987994667?w=500&q=80"
        n.contains("aguacate") -> "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=500&q=80"
        n.contains("papa") -> "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=500&q=80"
        n.contains("huevo") -> "https://images.unsplash.com/photo-1587486913049-53fc88980cfc?w=500&q=80"
        n.contains("pollo") -> "https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=500&q=80"
        n.contains("carne") || n.contains("res") || n.contains("cerdo") -> "https://images.unsplash.com/photo-1603048297172-c92544798d5e?w=500&q=80"
        else -> "https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=500&q=80" // Default fresh produce
    }
}
"""
if "fun getProductImage" not in content:
    content = content.replace("fun AdminScreen", helper_func + "\nfun AdminScreen")

# Update ProductDialog signature
content = content.replace(
    'fun ProductDialog(initialProduct: Product? = null, onDismiss: () -> Unit, onSave: (String, Double, Double, Double) -> Unit)',
    'fun ProductDialog(initialProduct: Product? = null, onDismiss: () -> Unit, onSave: (String, Double, Double, Double, String) -> Unit)'
)
content = content.replace(
    'var name by remember { mutableStateOf(initialProduct?.name ?: "") }',
    'var name by remember { mutableStateOf(initialProduct?.name ?: "") }\n    var imageUrl by remember { mutableStateOf(initialProduct?.imageUrl ?: "") }'
)
content = content.replace(
    'onSave(name, unitCost, autoGeneratedPrice, parsedStock)',
    'onSave(name, unitCost, autoGeneratedPrice, parsedStock, imageUrl)'
)

# Add imageUrl field to ProductDialog UI
dialog_field = """                Spacer(modifier = Modifier.height(12.dp))
                OutlinedTextField(
                    value = imageUrl,
                    onValueChange = { imageUrl = it },
                    label = { Text("URL de la Foto (Opcional)") },
                    modifier = Modifier.fillMaxWidth(),
                    shape = RoundedCornerShape(12.dp)
                )"""
content = content.replace(
    'shape = RoundedCornerShape(12.dp),\n                    keyboardOptions = androidx.compose.foundation.text.KeyboardOptions(keyboardType = androidx.compose.ui.text.input.KeyboardType.Number)\n                )',
    'shape = RoundedCornerShape(12.dp),\n                    keyboardOptions = androidx.compose.foundation.text.KeyboardOptions(keyboardType = androidx.compose.ui.text.input.KeyboardType.Number)\n                )' + dialog_field
)

# Fix the onSave call inside AdminInventoryScreen
content = content.replace(
    'onSave = { name, cost, price, stock ->',
    'onSave = { name, cost, price, stock, imageUrl ->'
)
content = content.replace(
    'viewModel.updateProduct(productToEdit!!.copy(name = name, cost = cost, price = price, stock = stock))',
    'viewModel.updateProduct(productToEdit!!.copy(name = name, cost = cost, price = price, stock = stock, imageUrl = imageUrl))'
)
content = content.replace(
    'viewModel.addProduct(Product(name = name, cost = cost, price = price, stock = stock))',
    'viewModel.addProduct(Product(name = name, cost = cost, price = price, stock = stock, imageUrl = imageUrl))'
)

with open('app/src/main/java/com/example/ui/screens/AdminScreen.kt', 'w') as f:
    f.write(content)
