package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF6B9B3C) // A fresh green from the banner
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE8F5E9)
val md_theme_light_onPrimaryContainer = Color(0xFF1B3D08)
val md_theme_light_secondary = Color(0xFFE6C229) // Soft yellow
val md_theme_light_onSecondary = Color(0xFF4A3A00)
val md_theme_light_secondaryContainer = Color(0xFFFFF4CE)
val md_theme_light_onSecondaryContainer = Color(0xFF5D4800)
val md_theme_light_tertiary = Color(0xFF8D6E63) // Warm brown for the crate
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFEFEBE9)
val md_theme_light_onTertiaryContainer = Color(0xFF3E2723)
val md_theme_light_background = Color(0xFFFCFDF6)
val md_theme_light_onBackground = Color(0xFF1A1C19)
val md_theme_light_surface = Color(0xFFFCFDF6)
val md_theme_light_onSurface = Color(0xFF1A1C19)
val md_theme_light_surfaceVariant = Color(0xFFDFE4D7)
val md_theme_light_onSurfaceVariant = Color(0xFF43483E)
val md_theme_light_outline = Color(0xFFEEE7E3)
val md_theme_light_outlineVariant = Color(0xFFF3EFEC)

val md_theme_dark_primary = Color(0xFFC5D9A5)
val md_theme_dark_onPrimary = Color(0xFF103700)
val md_theme_dark_primaryContainer = Color(0xFF1F5106)
val md_theme_dark_onPrimaryContainer = Color(0xFFE8F3D6)
val md_theme_dark_secondary = Color(0xFFBCAAA1)
val md_theme_dark_onSecondary = Color(0xFF271913)
val md_theme_dark_secondaryContainer = Color(0xFF3F2D27)
val md_theme_dark_onSecondaryContainer = Color(0xFFF3EFEC)
val md_theme_dark_tertiary = Color(0xFFFFB598)
val md_theme_dark_onTertiary = Color(0xFF5A1B0E)
val md_theme_dark_tertiaryContainer = Color(0xFF763222)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDBCB)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_background = Color(0xFF1D1B1A)
val md_theme_dark_onBackground = Color(0xFFFCF9F7)
val md_theme_dark_surface = Color(0xFF1D1B1A)
val md_theme_dark_onSurface = Color(0xFFFCF9F7)
val md_theme_dark_surfaceVariant = Color(0xFF4E443F)
val md_theme_dark_onSurfaceVariant = Color(0xFFD4C3BA)
val md_theme_dark_outline = Color(0xFF9E8E85)
val md_theme_dark_outlineVariant = Color(0xFF4E443F)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_onError = Color(0xFFFFFFFF)
